version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: templates/index.html
  upload: index\.html
- url: /stylesheets
  static_dir: stylesheets
- url: .*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
